################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/adc.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/delay.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/eeprom.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/fifo.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/gpio.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/gps.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/i2c.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/nvmm.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/systime.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/timer.c \
D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/uart.c 

OBJS += \
./system/adc.o \
./system/delay.o \
./system/eeprom.o \
./system/fifo.o \
./system/gpio.o \
./system/gps.o \
./system/i2c.o \
./system/nvmm.o \
./system/systime.o \
./system/timer.o \
./system/uart.o 

C_DEPS += \
./system/adc.d \
./system/delay.d \
./system/eeprom.d \
./system/fifo.d \
./system/gpio.d \
./system/gps.d \
./system/i2c.d \
./system/nvmm.d \
./system/systime.d \
./system/timer.d \
./system/uart.d 


# Each subdirectory must supply rules for building sources it contributes
system/adc.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/delay.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/delay.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/eeprom.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/eeprom.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/fifo.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/fifo.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/gpio.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/gps.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/gps.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/i2c.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/nvmm.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/nvmm.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/systime.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/systime.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/timer.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

system/uart.o: D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/system/uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32 -DSTM32L0 -DSTM32L071CBTx -DDEBUG -DSX1276MB1LAS -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DREGION_EU868 -DBOOTLOADER -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../common/LmHandler/packages" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/m2m-76-impulse-counter/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/cmsis" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../boards/mcu/stm32/STM32L0xx_HAL_Driver/Inc" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../mac/region" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../peripherals" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../radio" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../proto" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../libraries/nanopb" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../lora-protobuf/generator" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system" -I"D:/Work/Dmitriy/LoRaMac-node/loramac-node/src/apps/LoRaMac/classA/m2m-76-impulse-counter-bootloader/../../../../system/crypto" -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


